#!/usr/bin/env python3
"""Generate seed-nist-cmmc-policies.sql from ../policy-templates/nist-cmmc/*.md.

Converts the three NIST/CMMC policy templates into idempotent T-SQL inserts for
Policies / PolicyCategories / PolicyVariables / PolicyVersions, with the
{{token}} placeholders becoming PolicyVariables rows (question wording from
../policy-templates/client-intake-questionnaire.md, Part B).

The SQL is DATABASE-FIRST and idempotent: categories are matched by Name,
policies by Title, variables by (PolicyId, Key) — safe to run more than once
and safe against a DB that already has rows. Run it manually (e.g. Azure Portal
Query editor) against krewe-governance-db; never via migrations.

Usage: python3 generate_seed.py   (writes seed-nist-cmmc-policies.sql beside itself)
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
TEMPLATES = HERE.parent / "policy-templates" / "nist-cmmc"
OUT = HERE / "seed-nist-cmmc-policies.sql"

TOKEN = re.compile(r"\{\{\s*([A-Za-z0-9_.\-]+)\s*\}\}")

# The wizard question wording for each merge token — from
# policy-templates/client-intake-questionnaire.md, Part B (B1–B8).
QUESTIONS = {
    "Company.LegalName": ("Company legal name", "What is the organization's full legal name?", "text"),
    "Company.ShortName": ("Company short name", "What short name should policies use in-text?", "text"),
    "Company.Address": ("Primary business address", "What is the primary business address?", "textarea"),
    "IT.Manager": ("Policy owner / IT manager", "Who is the policy owner / IT manager (name + title)?", "text"),
    "IT.ProviderName": ("Managed IT provider", "Who is the managed IT provider?", "text"),
    "Policy.EffectiveDate": ("Policy effective date", "What effective date should this policy set carry?", "date"),
    "Policy.ReviewCadence": ("Policy review cadence", "How often will policies be reviewed?", "text"),
    "Training.Frequency": ("Training frequency", "How often is security awareness training delivered?", "text"),
}
# Part B order (B1..B8) → wizard SortOrder
ORDER = list(QUESTIONS.keys())

# (file, policy GUID if new, version GUID if new, category, category GUID if new, cat sort)
POLICIES = [
    ("device-and-application-inventory.md",
     "B1000000-0000-4000-8000-000000000001", "C1000000-0000-4000-8000-000000000001",
     "Configuration Management", "A1000000-0000-4000-8000-000000000001", 1),
    ("access-control.md",
     "B1000000-0000-4000-8000-000000000002", "C1000000-0000-4000-8000-000000000002",
     "Access Control", "A1000000-0000-4000-8000-000000000002", 2),
    ("awareness-and-training.md",
     "B1000000-0000-4000-8000-000000000003", "C1000000-0000-4000-8000-000000000003",
     "Awareness & Training", "A1000000-0000-4000-8000-000000000003", 3),
]

SUMMARIES = {
    "device-and-application-inventory.md":
        "How the client identifies, records, and maintains an accurate inventory of hardware "
        "and software. NIST SP 800-171 3.4.1-3.4.3 / CMMC 2.0 CM / CSF ID.AM-1,2. Draft - "
        "vCIO/legal review required before client issue.",
    "access-control.md":
        "How the client grants, manages, and revokes access to systems and data with least "
        "privilege. NIST SP 800-171 3.1.x / CMMC 2.0 AC / CSF PR.AC. Draft - vCIO/legal "
        "review required before client issue.",
    "awareness-and-training.md":
        "The client's security awareness and training program, distributed and acknowledged "
        "via Phin Security. NIST SP 800-171 3.2.1-3.2.3 / CMMC 2.0 AT / CSF PR.AT. Draft - "
        "vCIO/legal review required before client issue.",
}

TITLES = {
    "device-and-application-inventory.md": "Device & Application Inventory Policy",
    "access-control.md": "Access Control Policy",
    "awareness-and-training.md": "Security Awareness & Training Policy",
}


def body_of(path: Path) -> str:
    """Strip the YAML front-matter; the policy body is what gets merged/stored."""
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n.*?\n---\n\s*", text, re.DOTALL)
    return text[m.end():] if m else text


def q(s: str) -> str:
    """T-SQL N'...' literal."""
    return "N'" + s.replace("'", "''") + "'"


def main() -> None:
    lines = [
        "-- KREWE Governance — seed the three NIST/CMMC policy templates (milestone R2, NOC-54).",
        "-- GENERATED by generate_seed.py from ../policy-templates/nist-cmmc/ — edit the",
        "-- templates and regenerate rather than editing this file.",
        "--",
        "-- Idempotent + database-first: matches categories by Name, policies by Title,",
        "-- variables by (PolicyId, Key). Run manually against krewe-governance-db",
        "-- (noit-krwgov-0628.database.windows.net) — e.g. Azure Portal Query editor.",
        "-- NEVER run EF migrations/EnsureCreated against that database.",
        "",
        "SET XACT_ABORT ON;",
        "BEGIN TRANSACTION;",
        "",
        "-- Seed rows carry CreatedByUserId = empty GUID (system/seed; Users has no FK here).",
        "DECLARE @seedUser uniqueidentifier = '00000000-0000-0000-0000-000000000000';",
        "DECLARE @now datetime2 = SYSUTCDATETIME();",
        "",
    ]

    for fname, pol_guid, ver_guid, cat, cat_guid, cat_sort in POLICIES:
        body = body_of(TEMPLATES / fname)
        title = TITLES[fname]
        summary = SUMMARIES[fname]
        tokens = []
        for m in TOKEN.finditer(body):
            k = m.group(1)
            if k not in tokens:
                tokens.append(k)
        unknown = [t for t in tokens if t not in QUESTIONS]
        if unknown:
            raise SystemExit(f"{fname}: tokens with no questionnaire entry: {unknown}")
        tokens.sort(key=ORDER.index)

        sv = fname.replace("-", "_").replace(".md", "")
        lines += [
            f"-- ============ {title} ============",
            f"DECLARE @cat_{sv} uniqueidentifier =",
            f"    (SELECT TOP 1 Id FROM PolicyCategories WHERE Name = {q(cat)});",
            f"IF @cat_{sv} IS NULL",
            "BEGIN",
            f"    SET @cat_{sv} = '{cat_guid}';",
            "    INSERT INTO PolicyCategories (Id, Name, Description, SortOrder, CreatedAt, UpdatedAt)",
            f"    VALUES (@cat_{sv}, {q(cat)}, NULL, {cat_sort}, @now, @now);",
            "END;",
            "",
            f"DECLARE @pol_{sv} uniqueidentifier =",
            f"    (SELECT TOP 1 Id FROM Policies WHERE Title = {q(title)});",
            f"IF @pol_{sv} IS NULL",
            "BEGIN",
            f"    SET @pol_{sv} = '{pol_guid}';",
            "    INSERT INTO Policies (Id, Title, Summary, Content, CategoryId, AssignedClientIds,",
            "                          Status, CurrentVersion, CreatedByUserId, NextReviewDate, CreatedAt, UpdatedAt)",
            f"    VALUES (@pol_{sv}, {q(title)}, {q(summary)},",
            f"            {q(body)},",
            f"            @cat_{sv}, N'[]', N'draft', 1, @seedUser, NULL, @now, @now);",
            "",
            "    INSERT INTO PolicyVersions (Id, PolicyId, VersionNumber, Content, ChangeNotes, CreatedByUserId, CreatedAt)",
            f"    VALUES ('{ver_guid}', @pol_{sv}, 1,",
            f"            {q(body)},",
            f"            N'Initial seed from policy-templates/nist-cmmc/{fname} (0.1-draft).', @seedUser, @now);",
            "END;",
            "",
        ]
        for i, t in enumerate(tokens, start=1):
            label, question, input_type = QUESTIONS[t]
            lines += [
                f"IF NOT EXISTS (SELECT 1 FROM PolicyVariables WHERE PolicyId = @pol_{sv} AND [Key] = {q(t)})",
                "    INSERT INTO PolicyVariables (PolicyId, [Key], Label, Question, InputType, Options, IsUniversal, Required, SortOrder)",
                f"    VALUES (@pol_{sv}, {q(t)}, {q(label)}, {q(question)}, {q(input_type)}, NULL, 1, 1, {i});",
            ]
        lines.append("")

    lines += ["COMMIT TRANSACTION;", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
